### ISSUE TITLE
Closing about page closes application

### ISSUE THREAD

**Issue by Nivirx** [cop2805-bkj/cop2805-project3#5]
` setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);` on line 30 in AboutWindow.java is at fault. 

EDIT: The reason I didn't just fix it is because it has to do with whatever designer you used
We need to use just one GUI designer if we are going to use one because the *.form files have different
syntaxes so they don't work from IDE to IDE.

**Comment by LlanerasJ** [comment]
I used the net beans designer. I tried downloading IntelliJ but the designer in the IDE wouldn't pull up so i switched to net beans.

Will it not run on your IDE?

**Comment by LlanerasJ** [comment]
Bug is fixed!

**Comment by Nivirx** [comment]
Fixed by Pull request #6
